### ISSUE TITLE
error in Raft 1.0.4

### ISSUE THREAD

**Issue by Cronosus** [dakotahawkins/Raft-Inventory-Stack#1]
Hello, this mod is nice, but after last update of raft i get this error:

`ArgumentException: Undefined target method for patch method static System.Void RemoveCostMultiplePatch::Prefix(PlayerInventory __instance, System.Nullable`1& __state)
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0)
HarmonyLib.Harmony.<PatchAll>b__10_0 (System.Type type) (at <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0)
InventoryStack.Start () (at <437941bf082e4871a155677faf085ba6>:0)`

**Comment by dakotahawkins** [comment]
Hey @Cronosus, thank you for filing this. I just started playing the game again myself (like a lot of people, I'd imagine). I'll look in to this, hopefully pretty simple.

**Comment by dakotahawkins** [comment]
Fixed and published, happy rafting!

https://www.raftmodding.com/mods/inventory-stack
